// ---------------------------------------------------------------------------
// Regenerates src/data/regionRates.generated.ts from the Azure Retail Prices API.
//
// Run by hand (npm run pricing) rather than from the browser: prices.azure.com
// sends no Access-Control-Allow-Origin header, so a fetch from the SPA is blocked
// by CORS in every browser. Baking the rates in at build time keeps regional
// accuracy without a backend.
//
// https://learn.microsoft.com/en-us/rest/api/cost-management/retail-prices
// ---------------------------------------------------------------------------

import { writeFileSync } from 'node:fs';

/**
 * Three workload meters that exist in every region and are all priced at the
 * region's base capacity rate. Querying several means a rename of any one of
 * them degrades to a disagreement we can see rather than a silent wrong number.
 */
const WORKLOAD_METERS = ['Data Warehouse', 'Eventhouse', 'Power BI'];

const filter = [
  `serviceName eq 'Microsoft Fabric'`,
  `priceType eq 'Consumption'`,
  `unitOfMeasure eq '1 Hour'`,
  `(${WORKLOAD_METERS.map((m) => `armSkuName eq '${m}'`).join(' or ')})`,
].join(' and ');

const items = [];
let url = `https://prices.azure.com/api/retail/prices?currencyCode=USD&$filter=${encodeURIComponent(filter)}`;

while (url) {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Azure Retail Prices API returned ${res.status}`);
  }
  const page = await res.json();
  items.push(...page.Items);
  url = page.NextPageLink;
}

// The base capacity rate is the "<workload> Capacity Usage CU" meter. Serverless
// meters carry the same armSkuName but are priced separately, so exclude them.
const rates = new Map();
for (const item of items) {
  if (!item.meterName.endsWith('Capacity Usage CU')) continue;
  if (item.meterName.includes('Serverless')) continue;

  const seen = rates.get(item.armRegionName);
  if (seen != null && seen !== item.retailPrice) {
    throw new Error(
      `${item.armRegionName}: capacity meters disagree (${seen} vs ${item.retailPrice}). ` +
        `The API shape changed; check before trusting this output.`,
    );
  }
  rates.set(item.armRegionName, item.retailPrice);
}

if (rates.size === 0) {
  throw new Error('No capacity meters matched. The API shape changed.');
}

const sorted = [...rates].sort(([a], [b]) => a.localeCompare(b));
const fetchedOn = new Date().toISOString().slice(0, 10);

const body = `// GENERATED by scripts/fetch-pricing.mjs. Do not edit by hand.
// Azure Retail Prices API, USD, "<workload> Capacity Usage CU" meter.
// Refresh with: npm run pricing

/** Date this snapshot was taken, shown next to any price derived from it. */
export const PRICING_FETCHED_ON = '${fetchedOn}';

/** USD per capacity unit per hour, keyed by Azure ARM region name. */
export const CU_RATE_BY_REGION: Record<string, number> = {
${sorted.map(([region, price]) => `  ${region}: ${price},`).join('\n')}
};
`;

writeFileSync(new URL('../src/data/regionRates.generated.ts', import.meta.url), body);
console.log(`Wrote ${sorted.length} regions to src/data/regionRates.generated.ts (${fetchedOn}).`);
